### ISSUE TITLE
jsonへ置き替える

### ISSUE THREAD

**Issue by aj1m0n** [OguchiLab/Deep_Sort#2]
- [x] 複数車両を1つのjsonへ
- [x] 構造を考える

**Comment by aj1m0n** [comment]
{
"time":2021-06-01-10-00-00-00,
{
"id" : 1,
"xy": [x,y],
},
{
"id" : 2,
"xy": [x,y],
},
{
"id" : 3,
"xy": [x,y],
}
}

**Comment by niyalist** [comment]
自分を表現するID（IPアドレスかなあ）を入れて欲しいのと、座標は、点ではなく矩形で欲しいです。（いまのUDPバージョンと同じ）
ちなみに、矩形の下端の中心点を車の座標として扱っています。

**Comment by aj1m0n** [comment]
{
"IP":192.168.x.x,
"time":2021-06-01-10-00-00-00,

{
"id" : 1,
"xy": [x1,x2,y1,y2],
},
{
"id" : 2,
"xy":[x1,x2,y1,y2],
},
{
"id" : 3,
"xy":[x1,x2,y1,y2],
}
}

**Comment by aj1m0n** [comment]
> 自分を表現するID（IPアドレスかなあ）を入れて欲しいのと、座標は、点ではなく矩形で欲しいです。（いまのUDPバージョンと同じ）
> ちなみに、矩形の下端の中心点を車の座標として扱っています。

整形済み
{
    "IP": "192.168.x.x",
    "time": "2021-06-01-10-00-00-00",
    "data1": {
        "id": 1,
        "xy": [
            "x1",
            "y1",
            "x2",
            "y2"
        ]
    },
    "data2": {
        "id": 2,
        "xy": [
            "x1",
            "y1",
            "x2",
            "y2"
        ]
    },
    "data3": {
        "id": 3,
        "xy": [
            "x1",
            "y1",
            "x2",
            "y2"
        ]
    }
}

**Comment by aj1m0n** [comment]
修正
{"IP": ["192.168.1.1"], "date": ["2021-05-30T19:22:30.535587"], "data": {"1": [100, 100, 100, 100], "2": [200, 200, 200, 200], "3": [300, 300, 300, 300]}}

**Comment by aj1m0n** [comment]
#4 
add def create json
